config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources "committees" do
    resources "tickets"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/committee.rb
class Committee < ApplicationRecord
  belongs_to :community
  has_many :tickets
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :committees
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :committee
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  def index
    @committees = Committee.all
  end

  def show
    @committee = Committee.find(params[:id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    committee = Committee.find params[:committee_id]
    @ticket = committee.tickets.new(user: User.first)
  end

  def create
    committee = Committee.find params[:committee_id]
    ticket = committee.tickets.create!(params[:ticket].permit(:user_id, :title, :body))
    redirect_to ticket.committee
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/committees/index.html.erb
<h1>Committees</h1>

<ul>
  <% @committees.each do |committee| %>
    <li>
      <%= link_to committee.name, committee %>
    </li>
  <% end %>
</ul>

app/views/committees/show.html.erb
<h1><%= @committee.name %></h1>

<ul>

  <% @committee.tickets.each do |ticket| %>
    <li id="ticket-<%= ticket.id %>">
      <p><%= ticket.title %></p>
      <p><%= ticket.body %></p>
      <p>Posted by: <%= ticket.user.name %></p>
    </li>
  <% end %>

</ul>

<%= link_to 'New ticket', new_committee_ticket_path(@committee) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/create.html.erb
<h1>Tickets#create</h1>
<p>Find me in app/views/tickets/create.html.erb</p>

app/views/tickets/new.html.erb
<h1><%= @ticket.committee.name %>: Add a new ticket</h1>

<%= form_with model: [@ticket.committee, @ticket] do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.hidden_field :user_id %>
  <%= f.submit "Create ticket" %>
<% end %>